<?php
/**
 * @var $block \Student\PowerModule\Block\PowerBlock
 */


$block->getDbData();


if (!$block->getEnabled()) {
    return;
}


?>
<div style="background-color: <?= $block->getRandomColor(); ?>">
    <?= $block->show() ?>
    <?= __('<br>[Hello from template powerblock.phtml]'); ?>

    <hr>
    <?= $block->showMenuItems(); ?>
    <hr>
    <?= $block->showMenuItems2(); ?>
    <hr>
    my custom category name is: <?= $block->getMyCustomCategory(); ?>

    <hr>
    Database:
    <table border="2">
        <tr>
            <th>test</th>
            <th>upgrade_col</th>
        </tr>
        <?= $block->getDbData(); ?>
    </table>
</div>



