<?php
/**
 * @var $block \Student\PowerModule\Block\PowerBlock
 */

if (!$block->getEnabled()) {
    return;
}


?>
<div style="background-color: <?= $block->getRandomColor(); ?>">
    <?= $block->show() ?>
    <?= __('<br>[Hello from template powerblock.phtml]'); ?>

    <hr>
    <?= $block->showMenuItems(); ?>
    <hr>
    <?= $block->showMenuItems2(); ?>
    <hr>
    <?php
    $name  = '';
    $prods = $block->getMyCustomCategory($name);
    ?>

    my custom category name is: <?= $name ?>
    <br>pruducts in category:
    <br>
    <?php

    foreach ($prods as $item) {

        $price = strip_tags($item->getFormatedPrice());

        echo "id: {$item->getId()};
            name: {$item->getName()};
            price: {$price};
            <br>";
    }

    if (count($prods) < 1) {
        echo '<br>no products found';
    }
    ?>

    <hr>
    Database:
    <table border="2">
        <tr>
            <th>test</th>
            <th>upgrade_col</th>
        </tr>

        <?php $df = $block->getDbData();
        foreach ($df as $item) {
            echo "<tr><td> {$item['test']} </td><td>{$item['upgrade_col']}</td></tr>";
        }
        ?>

    </table>
</div>