<?php
/** \Student\PowerModule\Block\Widget\PowerWidget $block */
?>

<h2 id="powerwidget-title"><?= $block->getData('title'); ?></h2>


<div class="slider" style="border-style: dashed;"
     data-slick='{"slidesToShow": <?= (int)$block->getSlidesQuantity(); ?>, "slidesToScroll":<?= $block->getSlidesQuantity(); ?>}'>

    <?php
    for ($i = 0; $i < 10; $i++) {
        echo "<div><img src='{$block->getData('image')}'></div>";
    }
    ?>
</div>
<h3>PowerWidget</h3>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".slider").slick();
        });
    });
</script>