<?php
/** \Student\PowerModule\Block\Widget\PowerWidget $block */
?>

<h2 id="powerwidget-title"><?= $block->getData('title'); ?></h2>


<div class="slider" style="border-style: dashed;">

    <?php
    for ($i = 0; $i < 10; $i++) {
        echo "<div><img src='{$block->getData('image')}'></div>";
    }
    ?>
</div>
<h3>PowerWidget</h3>

<script type="text/x-magento-init">
    {
        "*" : {
            "slick.init":{
                "slidesQuantity": <?=$block->getData('slides_quantity');?>
            }
        }
    }
</script>
